"""litepub_norm - AST normalization pipeline for documentation platform.

This package implements a deterministic, AST-centric publishing system where:
- Prose is authored in .md/.rst
- Quantitative artifacts are generated by analysis code
- All synchronization/export/redaction flows are governed by semantic IDs + contracts

Pipeline stages:
1. Adapters - Convert format-specific constructs to canonical Div wrappers
2. Normalizer - Create canonical AST with registry metadata
3. Resolver - Replace computed placeholders with generated payload
4. Validator - Validate AST invariants and contracts
5. Filters - Produce target-specific documents (internal/external/dossier)
"""

# Normalization API (convenience re-exports from normalizer)
from .normalizer import normalize_file, normalize_text, Registry

# Normalization errors
from .errors import (
    NormalizationError,
    FenceMismatchError,
    FenceOverlapError,
    UnknownSemanticIdError,
    RegistryIncompleteError,
)

# Resolution module
from .resolver import (
    resolve,
    build_resolution_plan,
    load_registry,
    ResolutionConfig,
    ResolutionLimits,
    RegistrySnapshot,
    RegistryEntry,
    ResolutionPlan,
    ResolutionError,
    RegistryError,
    PlaceholderError,
    PayloadError,
    ValidationError,
    HashMismatchError,
    KindMismatchError,
)

# Validation module
from .validator import (
    validate_metric_v1,
    validate_table_simple_v1,
    validate_table_pandoc_v1,
    validate_figure_meta_v1,
    validate_resolved_document,
    DocumentValidationResult,
)

__all__ = [
    # Normalization
    "normalize_file",
    "normalize_text",
    "Registry",
    "NormalizationError",
    "FenceMismatchError",
    "FenceOverlapError",
    "UnknownSemanticIdError",
    "RegistryIncompleteError",
    # Resolution
    "resolve",
    "build_resolution_plan",
    "load_registry",
    "ResolutionConfig",
    "ResolutionLimits",
    "RegistrySnapshot",
    "RegistryEntry",
    "ResolutionPlan",
    "ResolutionError",
    "RegistryError",
    "PlaceholderError",
    "PayloadError",
    "ValidationError",
    "HashMismatchError",
    "KindMismatchError",
    # Validation
    "validate_metric_v1",
    "validate_table_simple_v1",
    "validate_table_pandoc_v1",
    "validate_figure_meta_v1",
    "validate_resolved_document",
    "DocumentValidationResult",
]
